# Generated by Django 4.1.4 on 2022-12-14 08:11

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="content", field=markdownx.models.MarkdownxField(),
        ),
    ]
